//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenTrip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JourneySite
    {
        public string journeyLocationId { get; set; }
        public string journeyId { get; set; }
        public string locationId { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Journey Journey { get; set; }
        public virtual Site Site { get; set; }
    }
}
