//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenTrip.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Feedback = new HashSet<Feedback>();
            this.Journey = new HashSet<Journey>();
            this.UserPerference = new HashSet<UserPerference>();
        }
    
        public string userId { get; set; }
        [DisplayName("密碼")]
        [Required(ErrorMessage = "密碼不可空白")]
        [StringLength(20, ErrorMessage = "密碼必須是6-20個字元", MinimumLength = 6)]
        public string password { get; set; }
        [DisplayName("年齡")]
        public int age { get; set; }
        [DisplayName("性別")]
        public string sex { get; set; }
        [DisplayName("帳號")]
        [Required(ErrorMessage = "帳號不可空白")]
        [StringLength(20, ErrorMessage = "帳號必須是6-20個字元", MinimumLength = 6)]
        public string accountName { get; set; }
        [DisplayName("姓名")]
        [Required(ErrorMessage = "姓名不可空白")]
        public string nickName { get; set; }
        public System.DateTime signUpTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journey> Journey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPerference> UserPerference { get; set; }
    }
}
